config/routes.rb
Rails.application.routes.draw do
  resources :wits

  resources :articles do
    resources :comments
    end

get "/comments", to: "comments#comments"

  resources :users

  root 'users#new'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/wit.rb
class Wit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret",
  except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

def update
  @article = Article.find(params[:id])

  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy

  redirect_to articles_path
end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret",
  only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  def comments
    @article = Article.all
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @wits = Wit.all
    @users = User.all
    @articles = Article.all
    @comments = Comment.all
  end
end

app/controllers/wits_controller.rb
class WitsController < ApplicationController
  before_action :set_wit, only: [:show, :edit, :update, :destroy]

  # GET /wits
  # GET /wits.json
  def index
    @wits = Wit.all
  end

  # GET /wits/1
  # GET /wits/1.json
  def show
  end

  # GET /wits/new
  def new
    @wit = Wit.new
  end

  # GET /wits/1/edit
  def edit
  end

  # POST /wits
  # POST /wits.json
  def create
    @wit = Wit.new(wit_params)

    respond_to do |format|
      if @wit.save
        format.html { redirect_to @wit, notice: 'Wit was successfully created.' }
        format.json { render :show, status: :created, location: @wit }
      else
        format.html { render :new }
        format.json { render json: @wit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wits/1
  # PATCH/PUT /wits/1.json
  def update
    respond_to do |format|
      if @wit.update(wit_params)
        format.html { redirect_to @wit, notice: 'Wit was successfully updated.' }
        format.json { render :show, status: :ok, location: @wit }
      else
        format.html { render :edit }
        format.json { render json: @wit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wits/1
  # DELETE /wits/1.json
  def destroy
    @wit.destroy
    respond_to do |format|
      format.html { redirect_to wits_url, notice: 'Wit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wit
      @wit = Wit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wit_params
      params.require(:wit).permit(:message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wits_helper.rb
module WitsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %>
      prohibited
        this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= form_for :article, url: article_path(@article), method:
:patch do |f| %>

<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %>
      prohibited
        this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%=f.submit %>
  </p>

<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>        <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

<br>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= form_for :article, url: articles_path do |f| %>

<% if @article.errors.any? %>
<div id="error_explanation">
  <h2>
  <%= pluralize(@article.errors.count, "error") %>
  prohibited
    this article from being saved:
  </h2>

  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%=f.submit %>
  </p>

<% end %>

<%= link_to 'List of Articles', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit Article', edit_article_path(@article) %> |
<%= link_to 'Back to Articles', articles_path %>

app/views/comments/comments.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comments.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comments.body %>
</p>



<p>
  <%= link_to 'Destroy Comment', [comments.article, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogAssignment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1 class="welcome">Welcome to the Blog</h1>


<div class="container">

<div class="row format">
  <header>
<%= link_to 'Home', new_user_path %>
<%= link_to 'Blog', new_article_path %>
<%= link_to 'Message', new_wit_path %>
  <a href="#">Archives</a>
  </header>
</div>

<br>

   <div class="row">
        <div class="content">
          <%= yield %>
        </div>
    </div>
</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="table-format">
    <%= f.label :firstname, "First Name: " %>
    <%= f.text_field :firstname %><br>
    <%= f.label :lastname, "Last Name: " %>
    <%= f.text_field :lastname %><br>
  </fieldset>

<br>

  <div class="actions">
    <%= f.submit "Create User" %>
  </div>
<% end %>

app/views/users/edit.html.erb
 <h1>Editing Users</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h2>Add User Information</h2>

<%= render 'form' %>

<%= link_to 'List of Users', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome to the Blog</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<h2>Please Enter your Information</h2>

<ul>
  <% @users.each do |user| %>
  <li>
    <%= link_to user.message, user_path(user) %> | <small>
    <%= time_ago_in_words(user.created_at) %> ago </small>
  </li>
  <% end %>
</ul>

app/views/wits/_form.html.erb
<%= form_for(@wit) do |f| %>
  <% if @wit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wit.errors.count, "error") %> prohibited this wit from being saved:</h2>

      <ul>
      <% @wit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wits/edit.html.erb
<h1>Editing Wit</h1>

<%= render 'form' %>

<%= link_to 'Show', @wit %> |
<%= link_to 'Back', wits_path %>

app/views/wits/index.html.erb
<p id="notice"><%= notice %></p>

<head>
  <title>Witter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<h1>Listing Wits</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<div class="container">
  <div class="row">
    <div class="content">
      <tbody>
        <% @wits.each do |wit| %>
          <tr>
            <td><%= wit.message %></td>
            <td><%= link_to 'Show', wit %></td>
            <td><%= link_to 'Edit', edit_wit_path(wit) %></td>
            <td><%= link_to 'Destroy', wit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </div>
  </div>
</div>
</table>


<br>

<%= link_to 'New Wit', new_wit_path %>

app/views/wits/new.html.erb
<h1>New Wit</h1>

<%= render 'form' %>

<%= link_to 'List of Wits', wits_path %>

app/views/wits/show.html.erb
<p id="notice"><%= notice %></p>

<%= @wit.message %>
<small><%= time_ago_in_words(@wit.created_at) %></small>

<div class="actions">
  <%= link_to 'Edit', edit_wit_path(@wit) %> |
  <%= link_to 'Back', wits_path %>
</div>